repos:
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: pytest
        language: system
        pass_filenames: false
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: trailing-whitespace
      - id: pretty-format-json
        files: \.json$
        args:
          - --autofix
  - repo: local
    hooks:
      - id: format-yaml
        name: format-yaml
        entry: find . -type f \( -name "*.yml" -o -name "*.yaml" -o -path "./.github" \) -exec yq --prettyPrint -i {} \;
        pass_filenames: false
        language: system
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
